FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install -g @angular/cli@21
RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build -- --configuration production

FROM nginx:alpine

COPY docker/frontend/nginx/default.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
