parameters:
    app.cors.allowed_origins:
        - 'http://localhost:4200'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\EventSubscriber\ApiCorsSubscriber:
        arguments:
            $allowedOrigins: '%app.cors.allowed_origins%'

    App\State\InvitadoDeleteProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $invitadoRepository: '@App\Repository\InvitadoRepository'
            $seleccionParticipantesEventoRepository: '@App\Repository\SeleccionParticipantesEventoRepository'


    App\EventListener\JwtCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    App\EventListener\JWTAuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }

    App\ApiPlatform\Doctrine\Extension\InscripcionOwnerExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }
