FROM node:20-alpine AS frontend_build

WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build -- --configuration production

FROM nginx:1.27-alpine

COPY docker/nginx/default.prod.conf /etc/nginx/conf.d/default.conf
COPY backend/public /var/www/html/public
COPY --from=frontend_build /app/frontend/dist/frontend/browser/ /var/www/angular/
